version: '3'  # version of compose format 
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:7.0.2
    hostname: "weather_mongodb"


